name: CI Workflow with nodeps CMake preset

on:
  push:
    branches:
    - 'master'
    - 'devel'
    paths-ignore:
      - 'experimentalSetups/**'
      - 'iCubTemplates/**'
      - 'tests/**'
      - '.github/**'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths-ignore:
      - 'experimentalSetups/**'
      - 'iCubTemplates/**'
      - 'tests/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: |
        sudo apt install -y cmake build-essential

    - name: Configure
      run: |
        cmake --preset nodeps

    - name: Build
      run: |
        cmake --build --preset nodeps

    - name: Install
      run: |
        cd build
        cmake --install .
