name: CI Workflow

on:
  push:
    branches:
    - 'master'
    - 'devel'
    paths-ignore:
      - 'experimentalSetups/**'
      - 'iCubTemplates/**'
      - 'tests/**'
      - '.github/**'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths-ignore:
      - 'experimentalSetups/**'
      - 'iCubTemplates/**'
      - 'tests/**'
      - '.github/**'
  workflow_dispatch:

env:
  DEPENDENCIES_DIR: '/dependencies'

jobs:
  dry-run:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/robotology/robots-configuration:latest

    steps:
    - uses: actions/checkout@main

    - name: Extend environment
      shell: bash
      run: |
        echo "${DEPENDENCIES_DIR}/install/bin" >> $GITHUB_PATH
        echo "YARP_DATA_DIRS=${DEPENDENCIES_DIR}/install/share/yarp:${DEPENDENCIES_DIR}/install/share/iCub:${DEPENDENCIES_DIR}/install/share/CER:${DEPENDENCIES_DIR}/install/share/navigation:${DEPENDENCIES_DIR}/install/share/ICUBcontrib" >> $GITHUB_ENV

    - name: Configure Tests
      shell: bash
      run: |
        cd ./tests/dry-run/
        ./configure-tests.sh

    - name: Tests
      shell: bash
      run: |
        cd ./tests/dry-run/build
        ctest --timeout 60 --output-on-failure -L run

    - name: Upload Output
      if: always()
      uses: actions/upload-artifact@main
      with:
        name: dry-run_${{ github.run_id }}
        path: tests/dry-run/build/dry-run_log_*.txt
        retention-days: 30
